export const homeData = [
  {
    icon: '/img/icon-1.png',
    title: 'Swap/Exchange',
    description:
      'Click here for any related issues with swapping and/or exchange of coins.',
    height: '40px',
    width: '36px',
  },
  {
    icon: '/img/icon-1.png',
    title: 'Stake and Unstake',
    description: 'Click here if you have issues with staking and unstaking .',
    height: '40px',
    width: '36px',
  },
  {
    icon: '/img/icon-1.png',
    title: 'Mint NFT',
    description: 'Click here to  mint your NFT  now ',
    height: '40px',
    width: '36px',
  },
  {
    icon: '/img/icon-1.png',
    title: 'Connect to Dapps',
    description:
      'Click here to connect decentralised web applications to mobile wallets or enable DApp on mobile wallets/extension.',
    height: '40px',
    width: '36px',
  },

  {
    icon: '/img/issue.png',
    title: 'Login Issues',
    description: 'Click here if you have issues logging into your wallet.',
    height: '64px',
    width: '64px',
  },
  {
    icon: '/img/fund.png',
    title: 'Missing Funds/Irregular token balance',
    description: 'Click here to recover lost/missing funds.',
    height: '48px',
    width: '48px',
  },
  {
    icon: '/img/gas.png',
    title: 'Exorbitant Gas Fees',
    description: 'Exorbitant Gas Fees',
    height: '48px',
    width: '48px',
  },
  {
    icon: '/img/deley.png',
    title: 'Transaction Delay',
    description:
      'Do you have issues with transactions being delayed? Kindly click here',
    height: '48px',
    width: '48px',
  },
  {
    icon: '/img/wallet.png',
    title: 'Kindly click here Folders Issues With Trading wallet',
    description:
      'Do you have probems with your trading account? Kindly click here.',
    height: '80px',
    width: '80px',
  },
  {
    icon: '/img/coin.png',
    title: 'Unable to purchase coins',
    description:
      'if your account is not recognized as a trusted payment source you may not be able to buy crypto and add coins Kindly click here and follow the process to get started.',
    height: '64px',
    width: '64px',
  },
  {
    icon: '/img/locked.png',
    title: 'Locked Account',
    description:
      'if you are logged out due to activity on the account Kindly click here.',
    height: '80px',
    width: '80px',
  },
];

export const walletData = [
  { img: '/img/trust-Wallet.png', title: 'Trust Wallet' },
  { img: '/img/aave.jpeg', title: 'AAVE Wallet' },
  { img: '/img/wallet-connect.jpeg', title: 'Wallet Connect' },
  { img: '/img/enjin.png', title: 'Enjin Wallet' },
  { img: '/img/mew.png', title: 'MEW Wallet' },
  { img: '/img/metamask.png', title: 'Metamask Wallet' },
  { img: '/img/digitex.png', title: 'Digitex Wallet' },
  { img: '/img/math.svg', title: 'Meth Wallet' },
  { img: '/img/solana.svg', title: 'Solana Wallet' },
  { img: '/img/autherum.png', title: 'Autherum Wallet' },
  { img: '/img/portis.png', title: 'Portis Wallet' },
  { img: '/img/tron.png', title: 'Tron wallet' },
  { img: '/img/cosmos.png', title: 'Cosmos Wallet' },
  { img: '/img/exodus.png', title: 'Exodus Wallet' },
  { img: '/img/polkadot.png', title: 'Lisk Wallet' },
  { img: '/img/kardiachain.png', title: 'Kardiachain Wallet' },
  { img: '/img/1inch.png', title: '1inch Wallet' },
  { img: '/img/bancor.png', title: 'Bancor Wallet' },
  { img: '/img/kava.png', title: 'Kava Wallet' },
  { img: '/img/elrond.png', title: 'Elron Wallet' },
  { img: '/img/algorand.png', title: 'Algorand Wallet' },
  { img: '/img/fantom.jpeg', title: 'Fantom Wallet' },
  { img: '/img/harmony.png', title: 'Harmony Wallet' },
  { img: '/img/raydium.png', title: 'Raydium Wallet' },
  { img: '/img/klever.jpeg', title: 'Klever Wallet' },
  { img: '/img/monero.png', title: 'Monero Wallet' },
  { img: '/img/formatic.png', title: 'Formatic Wallet' },
  { img: '/img/defiat.png', title: 'Defiat Wallet' },
  { img: '/img/skale.png', title: 'Skale Wallet' },
  { img: '/img/coinomi.png', title: 'Coinomi Wallet' },
  { img: '/img/atomic.jpeg', title: 'Atomic Wallet' },
  { img: '/img/jaxx.png', title: 'Jaxx Wallet' },
  { img: '/img/octofi.png', title: 'Octofi Wallet' },
];
